### ISSUE TITLE
Get started content page

### ISSUE THREAD

**Issue by david90** [SkygearIO/skygear-getstarted#4]
- tabs do not need state now

**Comment by bensonby** [comment]
- use markdown to write the content (to be compiled to html)
- to be reused as React components, with configurable props such as
 1. platform
 2. new vs existing
 3. whether to include top platform menu
 4. whether to include index for navigation (at top right, as in portal new design, but not in doc site)
- styling should not be included in the content page, i.e. the portal/doc site implements their own css
